### ISSUE TITLE
StyleCI

### ISSUE THREAD

**Issue by GrahamCampbell** [viacoin/viacoin.org#10]
StyleCI only checks PHP code, so the readme badge says that exactly 0 out of 0 files are passing, hence the green status.

**Comment by romanornr** [comment]
Oh thanks I forgot. I could use houndci but it seems to be only useful for js. 
Do you know any?

**Comment by GrahamCampbell** [comment]
houndci doesn't seem to actually do anything similar to StyleCI. StyleCI provides actual fixes across the whole codebase, but hound just comments on PRs. I'm not aware of any other service as complete as StyleCI.
