### ISSUE TITLE
Viacoin : Cannot connect to Electrum Network? Any Ideas? Mainteance Work?

### ISSUE THREAD

**Issue by Zete88** [viacoin/viacoin.org#26]
Hello, today i want to check my balance, so it cannot connect.  

do you have more nodes?

i have electrum wallet 2.8.3 actually.

thank so far

**Comment by romanornr** [comment]
Maintenance last night.

**The vialectrum servers are up again.**
Please note that the servers are hosted by third parties. 

For a 100% uptime, I recommend using your Ledger Nano S/Blue, Viacoin Core or Coinomi.
